const HOME_BODY_BACKGROUND_COLOR  = '#CCCCCC';
const START_BUILDING_BODY_BACKGROUND_COLOR  = '#CCCCCC';
const WATCH_MODEL_BODY_BACKGROUND_COLOR  = '#CCCCCC';
const UPPER_STRAP_BODY_BACKGROUND_COLOR  = '#CCCCCC';
const LOWER_STRAP_BODY_BACKGROUND_COLOR  = '#CCCCCC';
const LOOP_BODY_BACKGROUND_COLOR  = '#CCCCCC';
const ACCESSORIES_BODY_BACKGROUND_COLOR  = '#CCCCCC';
const PREVIEW_BODY_BACKGROUND_COLOR  = '#CCCCCC';
const ABOUT_BODY_BACKGROUND_COLOR  = '#CCCCCC';

export function getBodyClassName() {
    return 'bg-default';
}
